name: Outlet
version: '$version'
description: $description
author: TheLukeGuy
website: https://github.com/TheLukeGuy/outlet
api-version: '1.19'

main: sh.lpx.outlet.OutletPlugin
bootstrapper: sh.lpx.outlet.OutletBootstrap
